name: Run Streamlit Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4  # Choose the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Retrieve Secret
        run: echo "My secret is ${{ secrets.OPENAI_API_KEY }}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Run Streamlit Application
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: streamlit run app.py  # Replace with the correct command to run your Streamlit app
